name: gulp

on:
  push:
    branches: 
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install&gulp
      run: |
        npm i gulp gulp-terser gulp-minify-css -D && npx gulp
        gulp 
        
    - name: Commit
      run: |
        ls
        rm -rf node_modules
        git credential-manager uninstall
        
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: dist
        FOLDER: ./dist
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
