name: gulp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install&gulp
      run: |
        npm install gulp
        npm install gulp-uglify
        gulp
    - name: Commit
      run: |
        ls
        git config --global user.email Hexopp-bot@email.com
        git config --global user.name Hexopp-bot
        git add . -f
        git commit -m ":zap: Successful minify" -a --force
        
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.token }}
